name: Build

on:
  push:
    branches: [ main ]

env:
  PHP_VERSION: '7.4'
  ROOT_FOLDER: './'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create release archive
      run: |
        mkdir -p dist
        zip -r dist/wp-autolink-notion-${{ github.run_id }}.zip .
      working-directory: ${{ env.ROOT_FOLDER }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: wp-autolink-notion-${{ github.run_id }}.zip
        path: ${{ env.ROOT_FOLDER }}/dist/wp-autolink-notion-${{ github.run_id }}.zip
