name: Build

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Release Version env
        run: |
          VERSION=${{ github.event.release.tag_name }}
          echo "Release Version: ${VERSION//v}"
          echo "RELEASE_VERSION=${VERSION//v}" >> $GITHUB_ENV

      - name: Create artifact
        uses: montudor/action-zip@v1
        with:
          args: mkdir -p build && zip -X -r build/${{ github.event.repository.name }}.zip . -x *.git* bin** node_modules/\* .* "*/\.*" *.dist *.xml *.neon composer.lock package*.json tests** build**

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: build/${{ github.event.repository.name }}.zip

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: build/${{ github.event.repository.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
